language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
      addons:
        artifacts: 
          paths:
            - ./build/packages
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: ppa:beineri/opt-qt-5.11.3-xenial
          packages:
            - g++-7
            - qt511base
            - ninja-build
            - rpm
            - pandoc
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
         - SCRIPTS_PATH_EVAL="SCRIPTS_PATH=${TRAVIS_BUILD_DIR}/scripts/linux"
         - CPACK_GENERATOR="RPM;DEB"

    - os: osx
      compiler: clang
      osx_image: xcode9.2
      env:
        - SCRIPTS_PATH_EVAL="SCRIPTS_PATH=${TRAVIS_BUILD_DIR}/scripts/osx"
        - CPACK_GENERATOR="DragNDrop"
      addons:
        artifacts: 
          paths:
            - ./build/packages

env:
    global:
        - KLOGG_VERSION_EVAL='KLOGG_VERSION=19.01.0.$TRAVIS_BUILD_NUMBER'
        - COMMON_CMAKE_OPTS_EVAL='COMMON_CMAKE_OPTS="-G Ninja -DBUILD_NUMBER=$TRAVIS_BUILD_NUMBER -DCMAKE_BUILD_TYPE=Release -DBUILD_DOC=True"'

before_install:
 - '[ "$TRAVIS_OS_NAME" != linux ] || eval "${MATRIX_EVAL}"'
 - eval "${SCRIPTS_PATH_EVAL}"

install:
 - '[ "$TRAVIS_OS_NAME" != osx ] || ${SCRIPTS_PATH}/install_deps.sh'

before_script:
 - '[ "$TRAVIS_OS_NAME" != linux ] || source /opt/qt511/bin/qt511-env.sh'
 - mkdir build
 - cd build
 - eval "${COMMON_CMAKE_OPTS_EVAL}"
 - eval "${KLOGG_VERSION_EVAL}"
 - '[ "$TRAVIS_OS_NAME" != osx ] || cmake ${COMMON_CMAKE_OPTS} -DCMAKE_PREFIX_PATH=$(brew --prefix qt5) ..'
 - '[ "$TRAVIS_OS_NAME" != linux ] || cmake ${COMMON_CMAKE_OPTS} -DCMAKE_INSTALL_PREFIX=/usr ..'

script:
 - cmake --build .
 - ctest --verbose
 - '[ "$TRAVIS_OS_NAME" != osx   ] || ${SCRIPTS_PATH}/prepare_bundle.sh'
 - '[ "$TRAVIS_OS_NAME" != linux ] || ${SCRIPTS_PATH}/make_appimage.sh'
 - cpack --verbose -G "${CPACK_GENERATOR}"
 - '[ "$TRAVIS_OS_NAME" != linux ] || cp klogg-x86_64.AppImage packages/klogg-$KLOGG_VERSION-x86_64.AppImage'
